### ISSUE TITLE
Where is Mixin Consensus Mechanism？

### ISSUE THREAD

**Issue by yinqianwu** [MixinNetwork/mixin#1]
I am a big fan of Mixin, looking into Mixin since the beginning. Since Mixin is a blockchain project, I am hoping Mixin could be more transparent to investors? I have a few questions on the technical side. Where is Mixin Consensus Mechanism? Are you going to publicize the consensus algorithm in the future? How do you leverage TEE in the system? How BFT-DAG fit into the system? I am hoping you could give a brief answer.

**Comment by cedricfung** [comment]
The Mixin Consensus is not fully completed yet, we are still working on the final protocol. 

Sure we will publicize the consensus algorithm and the implementation. TEE is mainly used to secure Mixin private keys, BFT is what full nodes agree and DAG is another network connected by light nodes.
