### ISSUE TITLE
RPC request alwasy return {"error":"bad request"} after normal RPC result

### ISSUE THREAD

**Issue by learnforpractice** [MixinNetwork/mixin#100]
**Describe the bug**
RPC request alwasy return {"error":"bad request"} after normal RPC result

**To Reproduce**
Run the following Python code:
```python
import requests
data = {'method': 'getinfo', 'params': []}
headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
r = requests.post('http://127.0.0.1:8007', json=data, headers=headers)
print(r.text)
```

Got the output like this:

```
...
[0,0],"e4a9ef941e1dfe221391056be6a9a79e5b29d863d466e8a7eefe028d7d2e8385":[0,0],"f1b6abb60f743554c1e3df97faf17af3f7c8f2a2d1ac4ccdd394514ded442082":[0,0]}},"timestamp":"2021-10-06T11:05:31.000000001+08:00","uptime":"3m41.091330692s","version":"v0.13.4-BUILD_VERSION"}}{"error":"bad request"}
```

**Expected behavior**
Successfull RPC request should not return {"error":"bad request"} at the end of normal return

**Related log**
2021/10/06 11:17:01 server.go:3159: http: superfluous response.WriteHeader call from github.com/MixinNetwork/mixin/rpc.(*Render).render (http.go:60)

**Environment (please complete the following information):**
 - OS: macOS 11.6
 - Version v0.13.4-f8c5c31c2ee83263b3fb73f4bee1dda6db288755]

**Additional context**
Sounds like this issue originates from the following code:
https://github.com/MixinNetwork/mixin/blob/f8c5c31c2ee83263b3fb73f4bee1dda6db288755/rpc/http.go#L68

**Comment by cedricfung** [comment]
Fixed 040fd8c56925e129d04294ac9abd82dac75d0a4e
