### ISSUE TITLE
How do we add a new token or request one?

### ISSUE THREAD

**Issue by trosel** [MixinNetwork/mixin#114]
i am looking for the code where all the token definitions and bridges live, but can’t find it. 

if this code is not exposed, can we request a new token be added?

**Comment by cedricfung** [comment]
Is it an ERC20 token? If so you can follow the guide on this repository https://github.com/MixinNetwork/asset-profile

**Comment by trosel** [comment]
It is not an ERC-20 token. I was thinking of Grin actually. https://grin.mw/

@cedricfung is there an example implementation of other non-ethereum tokens?

**Comment by cedricfung** [comment]
It's possible to add grin to the kernel by making the domain validation rules, you can find existing rules in domains directory.
