### ISSUE TITLE
编译mixin二进制文件报错

### ISSUE THREAD

**Issue by wimgithub** [MixinNetwork/mixin#18]
$ go build
报如下错误: 
# github.com/marten-seemann/qtls
../../marten-seemann/qtls/common.go:1062:20: undefined: cpu.ARM64

**Comment by cedricfung** [comment]
Please use the latest golang version from https://golang.org

**Comment by wimgithub** [comment]
> Please use the latest golang version from https://golang.org

I am using the latest golang version 1.12.1
