### ISSUE TITLE
mixin go build Error????

### ISSUE THREAD

**Issue by wimgithub** [MixinNetwork/mixin#19]
Thank you!
`wim@wim-ubuntu1804:~/mixin$ go build
# github.com/lucas-clemente/quic-go/internal/crypto
../workspace/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.10.1/internal/crypto/key_derivation.go:46:37: cs.KeyLen undefined (type mint.CipherSuiteParams has no field or method KeyLen)
../workspace/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.10.1/internal/crypto/key_derivation.go:47:35: cs.IvLen undefined (type mint.CipherSuiteParams has no field or method IvLen)
# github.com/MixinNetwork/mixin/storage
../workspace/go/pkg/mod/github.com/!mixin!network/mixin@v0.1.13/storage/badger_cache.go:64:19: not enough arguments in call to txn.Commit
 have ()
 want (func(error))
../workspace/go/pkg/mod/github.com/!mixin!network/mixin@v0.1.13/storage/badger_genesis.go:33:19: not enough arguments in call to txn.Commit
 have ()
 want (func(error))
../workspace/go/pkg/mod/github.com/!mixin!network/mixin@v0.1.13/storage/badger_graph.go:47:19: not enough arguments in call to txn.Commit
 have ()
 want (func(error))
../workspace/go/pkg/mod/github.com/!mixin!network/mixin@v0.1.13/storage/badger_graph.go:125:19: not enough arguments in call to txn.Commit
 have ()
 want (func(error))
../workspace/go/pkg/mod/github.com/!mixin!network/mixin@v0.1.13/storage/badger_round.go:69:19: not enough arguments in call to txn.Commit
 have ()
 want (func(error))
../workspace/go/pkg/mod/github.com/!mixin!network/mixin@v0.1.13/storage/badger_round.go:116:19: not enough arguments in call to txn.Commit
 have ()
 want (func(error))
../workspace/go/pkg/mod/github.com/!mixin!network/mixin@v0.1.13/storage/badger_transaction.go:80:19: not enough arguments in call to txn.Commit
 have ()
 want (func(error))`

**Comment by jadeydi** [comment]
Works for me, maybe you can upgrade your Go to 1.12.1 first, then try again.

**Comment by wimgithub** [comment]
> Works for me, maybe you can upgrade your Go to 1.12.1 first, then try again.

I am using go 1.12.1 and using go mod to manage the library

**Comment by jadeydi** [comment]
I think you import the wrong `badger` or wrong version, here is the source code
https://github.com/dgraph-io/badger/blob/master/txn.go#L590
