### ISSUE TITLE
Fail on using rpc call

### ISSUE THREAD

**Issue by samohyes** [MixinNetwork/mixin#35]
I am trying to use the rpc with a local testnet. So I am able to start the local testnet with 

`$ mixin setuptestnet

$ mixin kernel -dir /tmp/mixin-7001 -port 7001
$ mixin kernel -dir /tmp/mixin-7002 -port 7002
$ mixin kernel -dir /tmp/mixin-7003 -port 7003
$ mixin kernel -dir /tmp/mixin-7004 -port 7004
$ mixin kernel -dir /tmp/mixin-7005 -port 7005
$ mixin kernel -dir /tmp/mixin-7006 -port 7006
$ mixin kernel -dir /tmp/mixin-7007 -port 7007`

However, when I tried 

`./mixin getroundlink

Post http://127.0.0.1:8239: dial tcp 127.0.0.1:8239: connect: connection refused
`
Can anyone help me out?
It failed.

**Comment by cedricfung** [comment]
The testnet start with ports [7001-7007], so you call the RPC with ports [8001-8007].
