### ISSUE TITLE
election routine peer error HandshakeTimeout: Crypto handshake did not complete in time.

### ISSUE THREAD

**Issue by jingzhehu** [MixinNetwork/mixin#4]
I followed the steps in README to setup a local testnet but was met with the following error `2018/12/01 12:11:46 election routine peer error HandshakeTimeout: Crypto handshake did not complete in time.` 

Could you help me resolve the issue ?

OS: macOS Mojave. 
go version: go1.11.2 darwin/amd64

**Comment by jingzhehu** [comment]
I just tried on a linux machine with Ubuntu 18.04 LTS and got the same error. 

go version:  go1.10.4 linux/amd64

**Comment by cedricfung** [comment]
Do you have a full log? I have made a test on macOS and Linux, all work as expected.

**Comment by jingzhehu** [comment]
Here's the log:

`$ ./mixin setuptestnet
[
  {
    "address": "XINSpeVc39gxEUNA5HnChXF3GtPNvyNeBtQqfcbDkjkwr6DjC3AHzPX5x397D2SswfwXfWjeDe8QxF8X9TDJJob2A52FUb2g",
    "balance": "20000",
    "mask": "a4b698fd6a3334f7287d528b6b38e2038754d86555c8a41c8277356a45923b0f"
  },
  {
    "address": "XINByo2o9YMPWdit9MRYE2WzP9QEkKNvTJpVfnBFbVfxa9mcGyEqr1jsw94B3jLXWaLtK3VxHyvxm613Gmf5NLEmtXNzY1FQ",
    "balance": "20000",
    "mask": "5f47b64f0015b17b621b7849c814c57a5ebb6d1ef010cf5464f97999f0b44207"
  },
  {
    "address": "XINBUHTLQ4SiwDzrnFwx89bDyJeR3Vd1dRDSsdk7eJm1zBqT61qwV8e6nxzkRvSp8RqVoqB5y4F5YuXY97wEEkF2Xp1VhH1e",
    "balance": "20000",
    "mask": "543202bc89f23083f765b80cab056cc6f55999f8648379b0ffb815cc02057302"
  },
  {
    "address": "XINEdvJgRDK2qdsUQGeJYUyQW7jwbPXP1rZJnUCAgD8Gm5fzuo88dTGr6L73exF4wpJXBsg4z82YuT7EpZfcgjWobQPkHuYZ",
    "balance": "20000",
    "mask": "8d7ed2aa5459d03f886a845356b8087a4c70a7817293ddc9aa471df5e1315b04"
  },
  {
    "address": "XIN8qsAVPb2cFv81KDoZ15N2eh3jSAntjmnVJYc31A4AQnrozXFA3gcTawkmBYy5ZLNxCVYaSmWQ33zCvppxaY6bUrorM85o",
    "balance": "20000",
    "mask": "7922b9acf3a98942382d3e96b8cae455f49bb99246c1d67c031ef59b71b45404"
  },
  {
    "address": "XINUZJUb28zASRfZx2AZ3SJkw8r2YxtpeDXmt9Po4qMgPuZdkpMkDNSZ4Ks3AANZ9n43ECZvAYeQwzLYUbrWW4eQeE8JAjca",
    "balance": "20000",
    "mask": "55d8fa4eea5293678c8b728664fa908ff6c0917c6057c3c9c010346658706d09"
  },
  {
    "address": "XINMX4ptWaxk5jiEVfUMdk4P6Yhy8Fkaentv454Z4jmSBchbi5TSaLPjpyBgKp5VF3Tjg4q1VLVumQNQSMdcjaE2CMMtWCC1",
    "balance": "20000",
    "mask": "7042b464a0cdeb96d9bd945b639f914fce2b0eb6581bc91706b7b9e4a9eca504"
  }
]
[
  {
    "address": "XINSpeVc39gxEUNA5HnChXF3GtPNvyNeBtQqfcbDkjkwr6DjC3AHzPX5x397D2SswfwXfWjeDe8QxF8X9TDJJob2A52FUb2g",
    "host": "127.0.0.1:7001"
  },
  {
    "address": "XINByo2o9YMPWdit9MRYE2WzP9QEkKNvTJpVfnBFbVfxa9mcGyEqr1jsw94B3jLXWaLtK3VxHyvxm613Gmf5NLEmtXNzY1FQ",
    "host": "127.0.0.1:7002"
  },
  {
    "address": "XINBUHTLQ4SiwDzrnFwx89bDyJeR3Vd1dRDSsdk7eJm1zBqT61qwV8e6nxzkRvSp8RqVoqB5y4F5YuXY97wEEkF2Xp1VhH1e",
    "host": "127.0.0.1:7003"
  },
  {
    "address": "XINEdvJgRDK2qdsUQGeJYUyQW7jwbPXP1rZJnUCAgD8Gm5fzuo88dTGr6L73exF4wpJXBsg4z82YuT7EpZfcgjWobQPkHuYZ",
    "host": "127.0.0.1:7004"
  },
  {
    "address": "XIN8qsAVPb2cFv81KDoZ15N2eh3jSAntjmnVJYc31A4AQnrozXFA3gcTawkmBYy5ZLNxCVYaSmWQ33zCvppxaY6bUrorM85o",
    "host": "127.0.0.1:7005"
  },
  {
    "address": "XINUZJUb28zASRfZx2AZ3SJkw8r2YxtpeDXmt9Po4qMgPuZdkpMkDNSZ4Ks3AANZ9n43ECZvAYeQwzLYUbrWW4eQeE8JAjca",
    "host": "127.0.0.1:7006"
  },
  {
    "address": "XINMX4ptWaxk5jiEVfUMdk4P6Yhy8Fkaentv454Z4jmSBchbi5TSaLPjpyBgKp5VF3Tjg4q1VLVumQNQSMdcjaE2CMMtWCC1",
    "host": "127.0.0.1:7007"
  }
]`

**Comment by jingzhehu** [comment]
Got it working. It was my fault for not starting all 7 local nodes. 

However, I'm not sure about how to interact with the nodes. 

> $ ./mixin getinfo
panic: Post http://127.0.0.1:8239: dial tcp 127.0.0.1:8239: connect: connection refused

goroutine 1 [running]:
main.main()
	/Users/hujingzhe/golang/src/github.com/MixinNetwork/mixin/main.go:146 +0x1087

> $ ./mixin getinfo -n 127.0.0.1:7001
panic: Post http://127.0.0.1:7001: dial tcp 127.0.0.1:7001: connect: connection refused

goroutine 1 [running]:
main.main()
	/Users/hujingzhe/golang/src/github.com/MixinNetwork/mixin/main.go:146 +0x1087
