### ISSUE TITLE
Distribute mint by node work

### ISSUE THREAD

**Issue by cedricfung** [MixinNetwork/mixin#48]
By the signature count in past 24 hours?

**Comment by Zds23gbo** [comment]
Надо смотреть с другой стороны.

**Comment by cedricfung** [comment]
0. Choose `0:00 UTC` as the time window boundary
1. Count the number of snapshots lead by a node as `L`
2. Count the number of snapshots sign by a node as `F`
3. The work a node contributes to the network is `W = 1.2L+F`
4. Calculate the average work `A` of all nodes by remove a largest and smallest
5. Compare `W` with `A` to get a normalized share `S` using a curve similar to https://www.curve.fi/
6. Distribute `XIN` by `S` proportionally

**Comment by cedricfung** [comment]
Done in v0.11.0 51a88d8068056cc4c423f35da4da2ecba557ad89
