### ISSUE TITLE
How to cross compile (build for Linux amd64 on Mac)

### ISSUE THREAD

**Issue by liusining** [MixinNetwork/mixin#58]
When compiling for a Linux amd64 server on a Mac with the command:  `GOOS=linux GOARCH=amd64 go build`, I got:

> \# github.com/valyala/gozstd
> ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/stream.go:14:48: undefined: DefaultCompressionLevel
> ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/stream.go:31:59: undefined: CDict
> ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/stream.go:35:64: undefined: CDict
> ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/stream.go:47:20: undefined: Writer
> ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/stream.go:56:22: undefined: NewWriterLevel
> ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/stream.go:101:61: undefined: DDict
> ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/stream.go:110:6: undefined: Reader
> ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/stream.go:117:8: undefined: NewReader

After reading [the gozstd document](https://github.com/valyala/gozstd#how-to-cross-compile-gozstd) and [some blogs](https://imantung.github.io/gist/go-build/), I installed some cross compilers with: `brew install FiloSottile/musl-cross/musl-cross`.

Then, I tried to build using `CC=x86_64-linux-musl-gcc CXX=x86_64-linux-musl-g++ GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build`, and got:

> \# github.com/valyala/gozstd
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/libzstd_linux_amd64.a(zdict.o): in function `ZDICT_analyzeEntropy':
> zdict.c:(.text+0x7ce): undefined reference to `__fprintf_chk'
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/libzstd_linux_amd64.a(zdict.o): in function `ZDICT_analyzePos':
> zdict.c:(.text+0x1832): undefined reference to `__fprintf_chk'
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: zdict.c:(.text+0x18c2): undefined reference to `__fprintf_chk'
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/libzstd_linux_amd64.a(zdict.o): in function `ZDICT_finalizeDictionary':
> zdict.c:(.text+0x1b24): undefined reference to `__fprintf_chk'
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/libzstd_linux_amd64.a(zdict.o): in function `ZDICT_trainFromBuffer_unsafe_legacy':
> zdict.c:(.text+0x1d54): undefined reference to `__fprintf_chk'
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/libzstd_linux_amd64.a(zdict.o):zdict.c:(.text+0x1dd4): more undefined references to `__fprintf_chk' follow
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/libzstd_linux_amd64.a(entropy_common.o): in function `FSE_readNCount':
> entropy_common.c:(.text+0x345): undefined reference to `__memcpy_chk'
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/libzstd_linux_amd64.a(fastcover.o): in function `FASTCOVER_buildDictionary.isra.6':
> fastcover.c:(.text+0x3a9): undefined reference to `__fprintf_chk'
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: fastcover.c:(.text+0x44f): undefined reference to `__fprintf_chk'
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: fastcover.c:(.text+0x488): undefined reference to `__fprintf_chk'
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/libzstd_linux_amd64.a(fastcover.o): in function `FASTCOVER_ctx_init':
> fastcover.c:(.text+0x8a0): undefined reference to `__fprintf_chk'
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: fastcover.c:(.text+0x8e6): undefined reference to `__fprintf_chk'
> /usr/local/Cellar/musl-cross/0.9.9/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: ../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/libzstd_linux_amd64.a(fastcover.o):fastcover.c:(.text+0xbc7): more undefined references to `__fprintf_chk' follow
> collect2: error: ld returned 1 exit status

How can I compile for Linux amd64 on a Mac?

**Comment by cedricfung** [comment]
Is it still a case?

**Comment by sunitakawane** [comment]
facing the same issue.When compiling for a Linux amd64 server on a Mac with the command: GOOS=linux GOARCH=amd64 go build, I got:

# github.com/valyala/gozstd
../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/stream.go:14:48: undefined: DefaultCompressionLevel
../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/stream.go:31:59: undefined: CDict
../../GO_PATH/pkg/mod/github.com/valyala/gozstd@v1.8.3/stream.go:35:64: undefined: CDict

**Comment by cedricfung** [comment]
I think we have removed valyala zstd usage, please make sure you are using the latest code.
