### ISSUE TITLE
Malleable aggregated public key

### ISSUE THREAD

**Issue by lamagle** [MixinNetwork/mixin#83]
**Describe the bug**
The `AggregatePublicKey` function does not check if each public key is valid. As a result, an attacker is able to produce a valid multi-party signature without the knowledge of other parties' private key.

**To Reproduce**
Suppose that there are 2 parties with public keys `PK_1`, `PK_2`, signing a message `msg`. The aggregated public key of these two parties is `PK_1 + PK_2`. 

One of the parties, say party 1, can produce a valid signature for `msg` by posting his fake public key `PK_1'` with the following property: `PK_1' + PK_2 = xG`, where `x` is known to party 1. In this case, the private key `x` is the aggregated private key for the two parties. Therefore, party 1 can sign `msg` without party 2 being involved.

**Expected behavior**
A proof of exponential should be used here to make sure a signer knows his private key.

**Comment by cedricfung** [comment]
Hi, this function is only intended to be used in the Cosi process. In this specific situation, all parties know all the public keys, and the aggregated public key should be same to all others' results. And they don't need this public key to do direct signature.
